### ISSUE TITLE
Use row-gap instead of "bootstrap" like grid

### ISSUE THREAD

**Issue by mfestNFQ** [nfqde/nfq-react-grid#63]
We would be more flexibel in frontend development, if we use "gap" instead of rows with negative margin and cols with padding,

**Comment by mfestNFQ** [comment]
@ckruppe the gap property was introduced for iOS in version 10.3, which was in the beginning of 2017.
In my opinion it's old enough :)

**Comment by ckruppe** [comment]
Lets have a look into germany usage numbers. (Because i know that for example MeinNeuesHaar the customer has ios 9)

**Comment by ckruppe** [comment]
Fixed for react grid.
